# Generated by Django 3.2.7 on 2021-09-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typerisk',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
